---
development:
  cloud_name: axizozuk
  api_key: '739826395421878'
  api_secret: _tyHkZqj-IbfHVgj-8ki6Iu-F9M
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: axizozuk
  api_key: '739826395421878'
  api_secret: _tyHkZqj-IbfHVgj-8ki6Iu-F9M
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: axizozuk
  api_key: '739826395421878'
  api_secret: _tyHkZqj-IbfHVgj-8ki6Iu-F9M
  enhance_image_tag: true
  static_image_support: false