# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password') if Rails.env.development?
# Product.create title: 'Iron Pharma Deca MİX 400 mg', description: 'Deca Mix 4 esterli Bir deca türevidir.Decadan kısaca bahsedecek olursak bulk amaçlı kullanılan en etkili maddedir.Definasyon döneminde kullanılması uygun olmaz.Bu sebebi Deca Vücuda kas kazanımı yaparken yanında tutacağı su kütlesinden dolayı hatlı görünümü engeller.Deca 19-a Grubu dahildir 17 grubuna göre çok daha yüksek anabolik güce sahiptir.Resöptörlere çok güçlü bağlanır yanında başka bir 19-a(örn trnbolone) grubu kullanıldığında resöptörü kapattığı için 2.19-a grubu maddemiz tam randımanlı çalışmayacağından dolayı başka bir anabolizon eklecekse 17 grubundan(örn:boldenon,primobolon) ekleme yapılmalıdır.', trademark: 'İron pharma', price: 180, category: "Enjeksiyon Steroidler", image: 
# File.new("#{Rails.root}/app/assets/images/IP1.png")
# Product.create title: 'Iron Pharma Deca 200 mg', description: 'Deca Mix 4 esterli Bir deca türevidir.Decadan kısaca bahsedecek olursak bulk amaçlı kullanılan en etkili maddedir.Definasyon döneminde kullanılması uygun olmaz.Bu sebebi Deca Vücuda kas kazanımı yaparken yanında tutacağı su kütlesinden dolayı hatlı görünümü engeller.Deca 19-a Grubu dahildir 17 grubuna göre çok daha yüksek anabolik güce sahiptir.Resöptörlere çok güçlü bağlanır yanında başka bir 19-a(örn trnbolone) grubu kullanıldığında resöptörü kapattığı için 2.19-a grubu maddemiz tam randımanlı çalışmayacağından dolayı başka bir anabolizon eklecekse 17 grubundan(örn:boldenon,primobolon) ekleme yapılmalıdır.', trademark: 'İron pharma', price: 150, category: "Enjeksiyon Steroidler", image: 
# File.new("#{Rails.root}/app/assets/images/IP2.png")
# Product.create title: 'Iron Pharma Boldenon 400 mg', description: 'Deca Mix 4 esterli Bir deca türevidir.Decadan kısaca bahsedecek olursak bulk amaçlı kullanılan en etkili maddedir.Definasyon döneminde kullanılması uygun olmaz.Bu sebebi Deca Vücuda kas kazanımı yaparken yanında tutacağı su kütlesinden dolayı hatlı görünümü engeller.Deca 19-a Grubu dahildir 17 grubuna göre çok daha yüksek anabolik güce sahiptir.Resöptörlere çok güçlü bağlanır yanında başka bir 19-a(örn trnbolone) grubu kullanıldığında resöptörü kapattığı için 2.19-a grubu maddemiz tam randımanlı çalışmayacağından dolayı başka bir anabolizon eklecekse 17 grubundan(örn:boldenon,primobolon) ekleme yapılmalıdır.', trademark: 'İron pharma', price: 180, category: "Enjeksiyon Steroidler", image: 
# File.new("#{Rails.root}/app/assets/images/IP3.png")
# Product.create title: 'Iron Pharma Tren Mix 150 mg', description: 'Deca Mix 4 esterli Bir deca türevidir.Decadan kısaca bahsedecek olursak bulk amaçlı kullanılan en etkili maddedir.Definasyon döneminde kullanılması uygun olmaz.Bu sebebi Deca Vücuda kas kazanımı yaparken yanında tutacağı su kütlesinden dolayı hatlı görünümü engeller.Deca 19-a Grubu dahildir 17 grubuna göre çok daha yüksek anabolik güce sahiptir.Resöptörlere çok güçlü bağlanır yanında başka bir 19-a(örn trnbolone) grubu kullanıldığında resöptörü kapattığı için 2.19-a grubu maddemiz tam randımanlı çalışmayacağından dolayı başka bir anabolizon eklecekse 17 grubundan(örn:boldenon,primobolon) ekleme yapılmalıdır.', trademark: 'İron pharma', price: 200, category: "Enjeksiyon Steroidler", image: 
# File.new("#{Rails.root}/app/assets/images/IP4.png")